---
# tasks file for crowd

- name: create system user
  user:
    name={{ crowd_user }}
    password={{ crowd_pass }}
    home={{ crowd_home }}
    system=yes
    shell=/bin/bash
  tags: crowd

- name: prepare files
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
    - { path: "{{ crowd_catalina }}", owner: "{{ crowd_user }}", group: "{{ crowd_user }}", mode: '0755', state: 'directory' }
  tags: crowd

- name: download package
  get_url:
    url={{ crowd_url }}
    dest={{ crowd_archive }}
    sha256sum={{ crowd_sha256 }}
  tags: crowd

- name: unarchive package
  shell: tar zxvf {{ crowd_archive }} -C {{ crowd_catalina }} --strip-components=1; chown -Rf {{ crowd_user }}:{{ crowd_user }} {{ crowd_catalina }}
  args:
    creates: "{{ crowd_catalina }}/start_crowd.sh"
  tags: crowd

- name: copy templates
  template:
    src="{{ item.template }}.j2"
    dest="/{{ item.template }}"
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { template: 'etc/init.d/crowd', owner: 'root', group: 'root', mode: '0755' }
    - { template: 'usr/share/crowd/apache-tomcat/bin/setenv.sh', owner: "{{ crowd_user }}", group: "{{ crowd_user }}", mode: '0644' }
    - { template: 'usr/share/crowd/apache-tomcat/conf/server.xml', owner: "{{ crowd_user }}", group: "{{ crowd_user }}", mode: '0644' }
  tags: crowd

- name: enable service
  service: name=crowd enabled=yes
  notify: restart crowd
  tags: crowd
