---
# tasks file for hswong3i.crowd

- name: stop service if upgrade
  service: name=crowd state=stopped
  when: crowd_upgrade == true
  notify: restart crowd
  tags: crowd

- name: remove legacy binary if upgrade
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
    - { path: "{{ crowd_catalina }}", owner: "{{ crowd_user }}", group: "{{ crowd_user }}", mode: '0755', state: 'absent' }
  when: crowd_upgrade == true
  notify: restart crowd
  tags: crowd

- name: create system user
  user:
    name={{ crowd_user }}
    password={{ crowd_pass }}
    home={{ crowd_home }}
    system=yes
    shell=/bin/bash
  notify: restart crowd
  tags: crowd

- name: prepare files
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
    - { path: "{{ crowd_catalina }}", owner: "{{ crowd_user }}", group: "{{ crowd_user }}", mode: '0755', state: 'directory' }
  notify: restart crowd
  tags: crowd

- name: download package
  get_url:
    url={{ crowd_url }}
    dest={{ crowd_archive }}
    sha256sum={{ crowd_sha256 }}
  notify: restart crowd
  tags: crowd

- name: unarchive package
  shell: tar zxvf {{ crowd_archive }} -C {{ crowd_catalina }} --strip-components=1; chown -Rf {{ crowd_user }}:{{ crowd_user }} {{ crowd_catalina }}
  args:
    creates: "{{ crowd_catalina }}/start_crowd.sh"
  notify: restart crowd
  tags: crowd

- name: copy templates
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { src: 'etc/init.d/crowd.j2', dest: '/etc/init.d/crowd', owner: 'root', group: 'root', mode: '0755' }
    - { src: 'usr/share/crowd/apache-tomcat/bin/setenv.sh.j2', dest: "{{ crowd_catalina }}/apache-tomcat/bin/setenv.sh", owner: "{{ crowd_user }}", group: "{{ crowd_user }}", mode: '0644' }
    - { src: 'usr/share/crowd/apache-tomcat/conf/server.xml.j2', dest: "{{ crowd_catalina }}/apache-tomcat/conf/server.xml", owner: "{{ crowd_user }}", group: "{{ crowd_user }}", mode: '0644' }
  notify: restart crowd
  tags: crowd

- name: enable service
  service: name=crowd enabled=yes
  notify: restart crowd
  tags: crowd
